version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: funds-postgres
    environment:
      POSTGRES_DB: fundsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: funds-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Local dev kolaylığı için güvenliği kapattık
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"